// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title HoCaToken
 * @author HoFi Protocol
 * @notice ERC-20 token representing Holonic Care — the unit of value for care work in HoFi
 * @dev Mintable only by authorized TaskRegistry contracts (MINTER_ROLE).
 *      Each Holón has a sovereign emission cap to prevent devaluation.
 *      Designed to be integrated with GenLayer ISCs for decentralized equity validation.
 *
 * Token Economics:
 * - Symbol: HOCA
 * - Decimals: 18 (standard ERC-20)
 * - Max supply per Holón: 1,000,000 HOCA (enforced on-chain)
 * - Minting: only via validated care task approval
 * - Burning: not implemented in MVP (governance decision for future)
 */
contract HoCaToken is ERC20, AccessControl {

    /// @notice Role granted to TaskRegistry contracts authorized to mint rewards
    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");

    /// @notice Maximum HOCA a single Holón can emit without inter-holonic staking approval
    uint256 public constant MAX_HOLON_SUPPLY = 1_000_000 * 10**18;

    /// @notice Tracks total HOCA emitted per Holón address
    /// @dev holonAddress => totalEmitted
    mapping(address => uint256) public holonEmitted;

    /**
     * @notice Emitted when a care task is rewarded with HOCA tokens
     * @param executor The address of the community member who completed the task
     * @param holon The Holón contract that authorized the emission
     * @param amount The HOCA amount rewarded (18 decimals)
     * @param taskId The unique identifier of the validated task
     */
    event TaskRewarded(
        address indexed executor,
        address indexed holon,
        uint256 amount,
        bytes32 indexed taskId
    );

    /**
     * @notice Deploys the HoCaToken and grants admin + minter roles to deployer
     * @dev Deployer should transfer MINTER_ROLE to TaskRegistry after deployment
     */
    constructor() ERC20("HoCa Token", "HOCA") {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(MINTER_ROLE, msg.sender);
    }

    /**
     * @notice Mints HOCA as a reward for a validated care task
     * @dev Only callable by addresses with MINTER_ROLE (TaskRegistry contracts).
     *      Enforces per-Holón emission cap defined by MAX_HOLON_SUPPLY.
     * @param executor The community member who completed the care task
     * @param holon The Holón address whose emission quota is consumed
     * @param amount The HOCA reward amount in wei (18 decimals)
     * @param taskId The unique task identifier generated by TaskRegistry
     */
    function mintReward(
        address executor,
        address holon,
        uint256 amount,
        bytes32 taskId
    ) external onlyRole(MINTER_ROLE) {
        require(executor != address(0), "HoCaToken: invalid executor address");
        require(amount > 0, "HoCaToken: reward amount must be greater than zero");
        require(
            holonEmitted[holon] + amount <= MAX_HOLON_SUPPLY,
            "HoCaToken: Holon emission cap reached"
        );

        holonEmitted[holon] += amount;
        _mint(executor, amount);

        emit TaskRewarded(executor, holon, amount, taskId);
    }

    /**
     * @notice Returns the total HOCA emitted by a specific Holón
     * @param holon The Holón address to query
     * @return Total HOCA emitted in wei (18 decimals)
     */
    function getHolonEmission(address holon) external view returns (uint256) {
        return holonEmitted[holon];
    }
}
